name: ContinuousIntegration

on:
  push:
    tags:
      - 'v*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Branch a usar como variable de entorno
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: set NOW
        run: |
              cat $GITHUB_ENV
              echo "NOW=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
              cat $GITHUB_ENV

      - name: set REPO_NAME
        run: |
              cat $GITHUB_ENV
              echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
              cat $GITHUB_ENV

      - name: set TAG_NAME
        run: |
              cat $GITHUB_ENV
              echo "TAG_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV
              cat $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v3
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.NOW }}, ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:${{ env.TAG_NAME }}, ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest
